--- #YAML:1.0
name:               ExtUtils-InferConfig
version:            1.04
abstract:           Infer Perl Configuration for non-running interpreters
author:
    - Steffen Mueller <smueller@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Spec:  0
    Test::More:  0
requires:
    IPC::Cmd:  0
    IPC::Run:  0
resources:
    repository:  http://svn.ali.as/cpan/trunk/ExtUtils-InferConfig
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
