# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ExtUtils-InferConfig
version:      1.00
version_from: lib/ExtUtils/InferConfig.pm
installdirs:  site
requires:
    IPC::Cmd:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
